namespace HighwayRenegade.Core.App
{
    /// <summary>
    /// The one place scene names are written down.
    ///
    /// They were previously duplicated as string literals across GameFlowManager and the
    /// menu screens, and had already drifted: the flow manager tried to load "TestRace"
    /// while the only scene in the project is "TestTrack". Nothing caught it, because a
    /// bad scene name is not a compile error - it is a silent failure at runtime, and the
    /// flow manager went on to change game state as though the load had succeeded.
    /// </summary>
    public static class SceneNames
    {
        /// <summary>Title screen and campaign entry point.</summary>
        public const string MainMenu = "MainMenu";

        /// <summary>Bike selection, upgrades and repairs between races.</summary>
        public const string Garage = "Garage";

        /// <summary>
        /// The playable track. Generated by TestTrackGenerator rather than authored, so it
        /// can be rebuilt from code and reviewed in a diff.
        /// </summary>
        public const string Race = "TestTrack";
    }
}
