name: Acquire Unity License Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request .alf Activation File
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-6000.0.38f1-android-3
    steps:
      - name: Generate Manual Activation File
        run: |
          /opt/unity/Editor/Unity -quit -batchmode -nographics -createManualActivationFile -logfile /dev/stdout || true
          find . -name "*.alf" -exec cp {} ./Unity_v6000.alf \;

      - name: Upload .alf Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: Unity_v6000.alf
          retention-days: 1
